// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNw9GSCPfPMH0TfJukny0XvLiJC_iwCAA',
    appId: '1:622350474294:web:47ea13df3af8ba49e10c97',
    messagingSenderId: '622350474294',
    projectId: 'shuppq-847d6',
    authDomain: 'shuppq-847d6.firebaseapp.com',
    storageBucket: 'shuppq-847d6.firebasestorage.app',
    measurementId: 'G-3287Z7KWBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxFlB9o2I6K8gm7mhpOd9etuYsYJdIaHQ',
    appId: '1:622350474294:android:f3b843b794c11814e10c97',
    messagingSenderId: '622350474294',
    projectId: 'shuppq-847d6',
    storageBucket: 'shuppq-847d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWfJ-X2H0uww0PGBdBHvqYli571NlJd6o',
    appId: '1:622350474294:ios:147e56579bb7bcdfe10c97',
    messagingSenderId: '622350474294',
    projectId: 'shuppq-847d6',
    storageBucket: 'shuppq-847d6.firebasestorage.app',
    iosBundleId: 'com.example.easyq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWfJ-X2H0uww0PGBdBHvqYli571NlJd6o',
    appId: '1:622350474294:ios:147e56579bb7bcdfe10c97',
    messagingSenderId: '622350474294',
    projectId: 'shuppq-847d6',
    storageBucket: 'shuppq-847d6.firebasestorage.app',
    iosBundleId: 'com.example.easyq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNw9GSCPfPMH0TfJukny0XvLiJC_iwCAA',
    appId: '1:622350474294:web:cd60b26f47ec07b4e10c97',
    messagingSenderId: '622350474294',
    projectId: 'shuppq-847d6',
    authDomain: 'shuppq-847d6.firebaseapp.com',
    storageBucket: 'shuppq-847d6.firebasestorage.app',
    measurementId: 'G-XBYRPGVNKC',
  );
}
